server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
        - id : tool-service
          uri: lb://tool-service
          predicates:
            - Path=/tool/**
          filters:
            - StripPrefix=1
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**
          filters:
            - StripPrefix=1
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
        - id: tariff-service
          uri: lb://tariff-service
          predicates:
            - Path=/tariff/**
          filters:
            - StripPrefix=1