server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #default-zone: http://localhost:8761/eureka
      default-zone: http://eureka-service:8761/eureka
  instance:
    #hostname: localhost
    hostname: gateway-service
    prefer-ip-address: true
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://127.0.0.1:*"
              - "http://localhost:*"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id : tool-service
          uri: lb://tool-service
          predicates:
            - Path=/api/tools/**

        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**

        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clients/**

        - id: tariff-service
          uri: lb://tariff-service
          predicates:
            - Path=/api/tariff/**

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**