server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/clients/**

        - id : tool-service
          uri: lb://TOOL-SERVICE
          predicates:
            - Path=/api/tools/**

        - id: kardex-service
          uri: lb://KARDEX-SERVICE
          predicates:
            - Path=/api/kardex/**

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/loans/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/reports/**

        - id: tariff-service
          uri: lb://TARIFF-SERVICE
          predicates:
            - Path=/api/tariff/**