apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3clients-deployment
  labels:
    app: 3clients
spec:
  selector:
    matchLabels:
      app: 3clients
  replicas: 1
  template:
    metadata:
      labels:
        app: 3clients
    spec:
      containers:
        - name: client-service
          image: eliaszngusach/client-service:latest
          # ARGS: Tienen la prioridad más alta sobre cualquier application.yml
          args:
            # URL lógica: Debe ser exacta a lo que dice tu Token (localhost)
            - "--spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/tooltrent-realm"
            # URL física: Es por donde el POD realmente sale a buscar las llaves a tu Windows
            - "--spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.minikube.internal:9090/realms/tooltrent-realm/protocol/openid-connect/certs"
          
          env:
          # 1. Configuración de Infraestructura
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8081"
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: "http://eureka-service:8761/eureka/"
          - name: SPRING_CLOUD_NETFLIX_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: "http://eureka-service:8761/eureka/"
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: "true"

          # 2. Base de Datos
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://host.minikube.internal:5432/clientservicedb"
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-user-credentials
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-user-credentials
                key: password

          # 3. Keycloak Client (Opcional, si usas login de servidor)
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
            value: "http://host.minikube.internal:9090/realms/toolrent-realm"
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: keycloak-client-secrets
                key: client-id
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-client-secrets
                key: client-secret

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: 3clients
  ports:
    - port: 8084
      targetPort: 8084